export const columns = [
    { 
        field: "id",
        headerName: "ID",
        width: 100,
        sortable: false 
    },
    {
        field: "userName",
        headerName: "Nombre de usuario",
        width: 150,
        sortable: false,
    },
    {
        field: "email",
        headerName: "Email",
        width: 300,
        sortable: false,
        valueGetter: (params: { row: { email: string; }; }) => `${params.row.email}`,
    },
    {
        field: "stack",
        headerName: "Stack",
        width: 150,
        sortable: false,
    },
    {
        field: "genero",
        headerName: "Género",
        width: 150,
        sortable: false,
    },
    {
        field: "data",
        headerName: "Suscripción",
        type: 'number',
        sortable: false,
        width: 200,
    },
];

export const rows = [
    {
        id: 1,
        userName: "JonMilburn",
        email: "JonMilburn@gmail.com",
        data: "02/03/2023",
        stack: "Front-end",
        genero: "Masculino",
    },
    {
        id: 2,
        userName: "Cersei",
        email: "Cersei98@gmail.com",
        data: "06/07/2023",
        stack: "Back-end",
        genero: "Masculino",
    },
    {
        id: 3,
        userName: "Marsk",
        email: "BrunoMarsk@gmail.com",
        data: "20/02/2023",
        stack: "Front-end",
        genero: "Masculino",
    },
    {
        id: 4,
        userName: "Arya",
        email: "AryaQulio@gmail.com",
        data: "10/12/2023",
        stack: "Front-end",
        genero: "Masculino",
    },
    {
        id: 5,
        userName: "Daenerys",
        email: "Daenerys45@gmail.com",
        data: "21/12/2023",
        stack: "Full-stack",
        genero: "Feminino",
    },
    {
        id: 6,
        userName: "Kather",
        email: "KatherFullop@gmail.com",
        data: "14/10/2023",
        stack: "Full-stack",
        genero: "Feminino",
    },
    {
        id: 7,
        userName: "Ferrara",
        email: "Ferrara10@gmail.com",
        data: "14/09/2023",
        stack: "Back-end",
        genero: "Masculino",
    },
    {
        id: 8,
        userName: "Rossini",
        email: "RossiniGS@gmail.com",
        data: "29/07/2023",
        stack: "Back-end",
        genero: "Feminino",
    },
    {
        id: 9,
        userName: "Harvey",
        email: "HarveyLBDP@gmail.com",
        data: "16/04/2023",
        stack: "Back-end",
        genero: "Masculino",
    },
    {
        id: 10,
        userName: "TyFullRex",
        email: "TyFullRex@gmail.com",
        data: "02/03/2023",
        stack: "Front-end",
        genero: "Otro",
    },
];